### PR TITLE
fix: don't overwrite a dependency that already exists in root Cargo.toml

### LINKED ISSUE #10: Support for features seems to be missing
I just ran this on one of our projects, and it totally wrecked it.
It looks like `features` support is missing, or not working.

For Example:
`chrono = { version = "0.4.31", features = ["serde"] }`
got replaced with
`chrono = "0.4.31"`

and
```
tokio = { version = "1.35.1", features = ["full"] }
tokio = "1.35.1"
```

### PR DESCRIPTION
**Pull request by BobrImperator**
- Checks if a package already exists on root Cargo.toml before attempting to include the ones inherited from member Cargo.tomls

#### Before
image

#### After
image

closes #10

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -91,12 +91,20 @@ pub fn auto_inherit() -> Result<(), anyhow::Error> {
...
-            workspace_deps,
-            package_name,
-            dep2toml_item(&shared2dep(source)),
-        );
-        was_modified = true;
+        if workspace_deps.get(package_name).is_some() {
+            eprintln!(
+                "`{}` won't be auto-inherited because it's already present in the root manifest.",
+                package_name
+            );
```
Comment (LukeMathWalker) [inline src/lib.rs:98]:
```suggestion
```

Comment (LukeMathWalker) [reply src/lib.rs]: If we arrive here, it means that the workspace dependency for that package had a version compatible with other instances of the same package across the workspace.  
Therefore we don't need to do anything, but it is incorrect to say that it won't be auto-inherited, because it will be.
